

var h2ElementJS=document.createElement("h2");
h2ElementJS.innerHTML="This div is generated by Javascript Dynamically";
        document.getElementById("divJs").append(h2ElementJS);

var h2Element=React.createElement("h2",{id:"h2Element"},"This div is generated by React Dynamically");
        var root=ReactDOM.createRoot(document.getElementById("divReact"));
        root.render(h2Element);