

var h2ElementJS=document.createElement("h2");
h2ElementJS.innerHTML="This div is generated by Javascript Dynamically";
        document.getElementById("divJs").append(h2ElementJS);

//Single Element
// var h2Element=React.createElement("h2",{id:"h2Element"},"This div is generated by React Dynamically");
//         var root=ReactDOM.createRoot(document.getElementById("divReact"));
//         root.render(h2Element);

//Multiple Elements
var parent=React.createElement("div",{id:"divParent"},

    [
        React.createElement("div",{id:"divFirstChild"},
            React.createElement("h4",{},"This is a First Grand Child, Who are siblings"))
            ,
            React.createElement("div",{id:"divSecondChild"},
                React.createElement("h4",{},"This is a Second Grand Child, Who are siblings"))

    ]);

    var root=ReactDOM.createRoot(document.getElementById("divReact"));
        root.render(parent);